### ISSUE TITLE
Switching from Desktop to Tablet with story open

### ISSUE THREAD

**Issue by KushalP** [PaulKinlan/ioreader#18]
See screenshot:

![Failing UI](http://i.imgur.com/Bq8PJ.png)

There are other cases where this happens, but it seems to be consistent in the above case. I'll see if I can reproduce the others with a script to see if it's a timing thing.

**Comment by PaulKinlan** [comment]
I think this is because this view was designed for WebKit.... will sort it.

**Comment by KushalP** [comment]
This is quite clearly out of date. Closing 👌
