### ISSUE TITLE
32 image tags with empty src values

### ISSUE THREAD

**Issue by KushalP** [PaulKinlan/ioreader#19]
You should be able to spot this using something like [Dom Monster!](http://mir.aculo.us/dom-monster/)

The drawbacks of this are explained well here: http://www.nczonline.net/blog/2009/11/30/empty-image-src-can-destroy-your-site/

**Comment by PaulKinlan** [comment]
I need to decide if I want to remove the image from the DOM if there is no src, or simply use a placeholder image.  I am leaning more towards no img element to save on resources.

**Comment by PaulKinlan** [comment]
This also actually explains a bug I was seeing when we demoed this at IO. - Good spot.
